version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./var:/var/www/html/var
    environment:
      DATABASE_URL: "postgresql://realmeduser:password@db:5432/realmed?serverVersion=13&charset=utf8"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: symfony_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: realmeduser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: realmed
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
